### PR TITLE
Add test configs

### PR DESCRIPTION
**Pull request by deyanstoyanov10**

### CODE REVIEW

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

**Plan Error**
```
running "/atlantis/bin/terraform1.4.6 plan -input=false -refresh -out \"/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test/default.tfplan\"" in "/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test": exit status 1
╷
│ Error: Not enough function arguments
│ 
│   on test-configurations.tf line 2, in locals:
│    2:   ms1_configurations = fileset("${path.module}/microservices/ms1/*.json")
│     ├────────────────
│     │ while calling fileset(path, pattern)
│     │ path.module is "."
│ 
│ Function "fileset" expects 2 argument(s). Missing value for "pattern".
╵

```

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

**Plan Error**
```
running "/atlantis/bin/terraform1.4.6 plan -input=false -refresh -out \"/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test/default.tfplan\"" in "/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test": exit status 1
╷
│ Error: Too many function arguments
│ 
│   on test-configurations.tf line 8, in module "ms1_values":
│    8:   for_each = { for file in local.ms1_configurations : basename(file, ".json") => jsondecode(file("${path.module}/microservices/ms1/${file}")) }
│ 
│ Function "basename" expects only 1 argument(s).
╵

```

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/atlantis/bin/terraform1.4.6 plan -input=false -refresh -out \"/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test/default.tfplan\"" in "/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test": exit status 1

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Invalid value for input variable
│ 
│   on test-configurations.tf line 12, in module "ms1_values":
│   12:   key_value = each.value
│ 
│ The given value is not suitable for
│ module.ms1_values["test.json"].var.key_value declared at
│ .terraform/modules/ms1_values/variables.tf:5,1-21: string required.
╵


```
</details>

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.ms1_values["test.json"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms1/test.json"
          + value  = jsonencode(
                {
                  + test1 = "test2"
                }
            )
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d consul-kv/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=deyanstoyanov10%252Fconsul-terraform%252Fconsul-kv%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d consul-kv/test`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/atlantis/bin/terraform1.4.6 plan -input=false -refresh -out \"/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test/default.tfplan\"" in "/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test": exit status 1
╷
│ Error: Invalid for_each argument
│ 
│   on test-configurations.tf line 20, in module "ms1_values":
│   20:   for_each = local.microservices_configurations
│     ├────────────────
│     │ local.microservices_configurations is tuple with 1 element
│ 
│ The given "for_each" argument value is unsuitable: the "for_each" argument
│ must be a map, or set of strings, and you have provided a value of type
│ tuple.
╵

```
</details>

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/atlantis/bin/terraform1.4.6 plan -input=false -refresh -out \"/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test/default.tfplan\"" in "/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test": exit status 1
╷
│ Error: Invalid "each" attribute
│ 
│   on test-configurations.tf line 23, in module "ms1_values":
│   23:   key_path = "${each.microservice_key_prefix}${each.microservice_key_name}"
│ 
│ The "each" object does not have an attribute named
│ "microservice_key_prefix". The supported attributes are each.key and
│ each.value, the current key and value pair of the "for_each" attribute set.
╵
╷
│ Error: Invalid "each" attribute
│ 
│   on test-configurations.tf line 23, in module "ms1_values":
│   23:   key_path = "${each.microservice_key_prefix}${each.microservice_key_name}"
│ 
│ The "each" object does not have an attribute named "microservice_key_name".
│ The supported attributes are each.key and each.value, the current key and
│ value pair of the "for_each" attribute set.
╵
╷
│ Error: Invalid "each" attribute
│ 
│   on test-configurations.tf line 24, in module "ms1_values":
│   24:   key_value = each.microservice_configuration
│ 
│ The "each" object does not have an attribute named
│ "microservice_configuration". The supported attributes are each.key and
│ each.value, the current key and value pair of the "for_each" attribute set.
╵

```
</details>

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.ms1_values["test.json.test/ms1.{\n    \"test1\": \"test2\"\n}"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms1/test.json"
          + value  = jsonencode(
                {
                  + test1 = "test2"
                }
            )
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d consul-kv/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=deyanstoyanov10%252Fconsul-terraform%252Fconsul-kv%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d consul-kv/test`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"test2\"\n}"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms1/test"
          + value  = jsonencode(
                {
                  + test1 = "test2"
                }
            )
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d consul-kv/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=deyanstoyanov10%252Fconsul-terraform%252Fconsul-kv%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d consul-kv/test`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by deyanstoyanov10** [comment]
atlantis apply

**Comment by deyanstoyanov10** [comment]
Ran Apply for dir: `consul-kv/test` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by PlatformCIBuilder — APPROVED** [review]

**Comment by deyanstoyanov10** [comment]
atlantis apply

**Comment by deyanstoyanov10** [comment]
Ran Apply for dir: `consul-kv/test` workspace: `default`

```diff
module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"test2\"\n}"].consul_keys.this: Creating...
module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"test2\"\n}"].consul_keys.this: Creation complete after 0s [id=consul]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by deyanstoyanov10** [comment]
atlantis plan

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

**Plan Error**
```
The default workspace at path consul-kv/test is currently locked by another command that is running for this pull request.
Wait until the previous command is complete and try again.
```

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"dynamic change\"\n}"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms1/test"
          + value  = jsonencode(
                {
                  + test1 = "dynamic change"
                }
            )
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d consul-kv/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=deyanstoyanov10%252Fconsul-terraform%252Fconsul-kv%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d consul-kv/test`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by deyanstoyanov10** [comment]
atlantis apply

**Comment by deyanstoyanov10** [comment]
Ran Apply for dir: `consul-kv/test` workspace: `default`

```diff
module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"dynamic change\"\n}"].consul_keys.this: Creating...
module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"dynamic change\"\n}"].consul_keys.this: Creation complete after 0s [id=consul]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"dynamic change\"\n}"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms1/test"
          + value  = jsonencode(
                {
                  + test1 = "dynamic change"
                }
            )
        }
    }

  # module.test_unit_configurations["test2.test/ms2.{\n    \"test2\": \"test2\"\n}"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms2/test2"
          + value  = jsonencode(
                {
                  + test2 = "test2"
                }
            )
        }
    }

  # module.test_unit_configurations["test3.test/ms2.{\n    \"test3\": \"test3\"\n}"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms2/test3"
          + value  = jsonencode(
                {
                  + test3 = "test3"
                }
            )
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d consul-kv/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=deyanstoyanov10%252Fconsul-terraform%252Fconsul-kv%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d consul-kv/test`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by deyanstoyanov10** [comment]
atlantis apply

**Comment by deyanstoyanov10** [comment]
Ran Apply for dir: `consul-kv/test` workspace: `default`

```diff
module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"dynamic change\"\n}"].consul_keys.this: Creating...
module.test_unit_configurations["test3.test/ms2.{\n    \"test3\": \"test3\"\n}"].consul_keys.this: Creating...
module.test_unit_configurations["test2.test/ms2.{\n    \"test2\": \"test2\"\n}"].consul_keys.this: Creating...
module.test_unit_configurations["test2.test/ms2.{\n    \"test2\": \"test2\"\n}"].consul_keys.this: Creation complete after 0s [id=consul]
module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"dynamic change\"\n}"].consul_keys.this: Creation complete after 0s [id=consul]
module.test_unit_configurations["test3.test/ms2.{\n    \"test3\": \"test3\"\n}"].consul_keys.this: Creation complete after 0s [id=consul]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/atlantis/bin/terraform1.4.6 plan -input=false -refresh -out \"/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test/default.tfplan\"" in "/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test": exit status 1
╷
│ Error: Unsupported argument
│ 
│   on test-configurations.tf line 25, in module "test_ms1":
│   25:   microservice_name = "ms1"
│ 
│ An argument named "microservice_name" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on test-configurations.tf line 27, in module "test_ms1":
│   27:   microservice_key_name = replace(each.key, ".json", "")
│ 
│ An argument named "microservice_key_name" is not expected here.
╵

```
</details>

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

**Plan Error**
```
running "/atlantis/bin/terraform1.4.6 plan -input=false -refresh -out \"/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test/default.tfplan\"" in "/atlantis/repos/deyanstoyanov10/consul-terraform/1/default/consul-kv/test": exit status 1
╷
│ Error: Invalid reference
│ 
│   on test-configurations.tf line 25, in module "test_ms1":
│   25:   for_each = fileset("${configuration_path}/ms1", "*.json")
│ 
│ A reference to a resource type must be followed by at least one attribute
│ access, specifying the resource name.
╵

```

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.test_ms1["test.json"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms1/test"
          + value  = jsonencode(
                {
                  + test1 = "dynamic change"
                }
            )
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d consul-kv/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=deyanstoyanov10%252Fconsul-terraform%252Fconsul-kv%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d consul-kv/test`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by deyanstoyanov10** [comment]
atlantis apply

**Comment by deyanstoyanov10** [comment]
Ran Apply for dir: `consul-kv/test` workspace: `default`

```diff
module.test_ms1["test.json"].consul_keys.this: Creating...
module.test_ms1["test.json"].consul_keys.this: Creation complete after 0s [id=consul]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by deyanstoyanov10** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `consul-kv/test` workspace: `default`

**Pull request merged**
