### PR TITLE
Add configs for ms2

### PR DESCRIPTION
**Pull request by deyanstoyanov10**

### CODE REVIEW

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.test_ms1["test.json"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms1/test"
          + value  = jsonencode(
                {
                  + test1 = "dynamic change"
                }
            )
        }
    }

  # module.test_ms2["test2.json"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms2/test2"
          + value  = jsonencode(
                {
                  + test2 = "test2"
                }
            )
        }
    }

  # module.test_ms2["test3.json"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms2/test3"
          + value  = jsonencode(
                {
                  + test3 = "test3"
                }
            )
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d consul-kv/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=deyanstoyanov10%252Fconsul-terraform%252Fconsul-kv%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d consul-kv/test`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by deyanstoyanov10** [comment]
Ran Plan for dir: `consul-kv/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"dynamic change\"\n}"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms1/test"
          + value  = jsonencode(
                {
                  + test1 = "dynamic change"
                }
            )
        }
    }

  # module.test_unit_configurations["test2.test/ms2.{\n    \"test2\": \"test2\"\n}"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms2/test2"
          + value  = jsonencode(
                {
                  + test2 = "test2"
                }
            )
        }
    }

  # module.test_unit_configurations["test3.test/ms2.{\n    \"test3\": \"test3\"\n}"].consul_keys.this will be created
+ resource "consul_keys" "this" {
      + datacenter = "dev"
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = "test/ms2/test3"
          + value  = jsonencode(
                {
                  + test3 = "test3"
                }
            )
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d consul-kv/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=deyanstoyanov10%252Fconsul-terraform%252Fconsul-kv%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d consul-kv/test`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by deyanstoyanov10** [comment]
atlantis apply

**Comment by deyanstoyanov10** [comment]
Ran Apply for dir: `consul-kv/test` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by PlatformCIBuilder — APPROVED** [review]

**Comment by deyanstoyanov10** [comment]
atlantis apply

**Comment by deyanstoyanov10** [comment]
Ran Apply for dir: `consul-kv/test` workspace: `default`

```diff
module.test_unit_configurations["test3.test/ms2.{\n    \"test3\": \"test3\"\n}"].consul_keys.this: Creating...
module.test_unit_configurations["test2.test/ms2.{\n    \"test2\": \"test2\"\n}"].consul_keys.this: Creating...
module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"dynamic change\"\n}"].consul_keys.this: Creating...
module.test_unit_configurations["test2.test/ms2.{\n    \"test2\": \"test2\"\n}"].consul_keys.this: Creation complete after 0s [id=consul]
module.test_unit_configurations["test3.test/ms2.{\n    \"test3\": \"test3\"\n}"].consul_keys.this: Creation complete after 0s [id=consul]
module.test_unit_configurations["test.test/ms1.{\n    \"test1\": \"dynamic change\"\n}"].consul_keys.this: Creation complete after 0s [id=consul]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

**Comment by deyanstoyanov10** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `consul-kv/test` workspace: `default`

**Pull request merged**
